services:
  - type: web
    name: ajgl-asbl
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn ajgl_project.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ajgl-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*.onrender.com"

databases:
  - name: ajgl-db
    plan: free