# Generated by Django 6.0.4 on 2026-05-03 09:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cellule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la cellule')),
                ('quartier', models.CharField(max_length=100, verbose_name='Quartier')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(max_length=50, verbose_name='Pays')),
                ('responsable', models.CharField(max_length=100, verbose_name='Nom du responsable')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone du responsable')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Cellule',
                'verbose_name_plural': 'Cellules',
                'ordering': ['pays', 'ville', 'quartier'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'événement")),
                ('type_event', models.CharField(choices=[('formation', 'Formation professionnelle'), ('apostolat', 'Apostolat / Visite sociale'), ('exposition', 'Exposition culturelle et artistique'), ('culturel', 'Activité culturelle'), ('sportif', 'Activité sportive (match de football)'), ('celebration', 'Célébration / Anniversaire'), ('assistance', 'Assistance humanitaire'), ('reunion', 'Réunion / Assemblée'), ('autre', 'Autre')], max_length=50, verbose_name="Type d'événement")),
                ('description', models.TextField(verbose_name='Description')),
                ('date_debut', models.DateTimeField(verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('lieu', models.CharField(max_length=200, verbose_name='Lieu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/', verbose_name='Image principale')),
                ('galerie_images', models.TextField(blank=True, help_text='URLs des images supplémentaires (séparées par des virgules)', null=True)),
                ('nombre_participants', models.IntegerField(default=0, verbose_name='Nombre de participants')),
                ('nombre_jumeaux_present', models.IntegerField(default=0, verbose_name='Nombre de jumeaux présents')),
                ('nombre_parents_present', models.IntegerField(default=0, verbose_name='Nombre de parents présents')),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], default='a_venir', max_length=20, verbose_name='Statut')),
                ('est_visible_site', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
                ('compte_rendu', models.TextField(blank=True, null=True, verbose_name='Compte-rendu / Résultats')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('pays', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pays')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom_complet', models.CharField(max_length=100)),
                ('adresse', models.TextField(help_text='Commune, Quartier, Avenue')),
                ('pays', models.CharField(choices=[('RDC', 'République Démocratique du Congo'), ('Rwanda', 'Rwanda'), ('Burundi', 'Burundi')], default='RDC', max_length=20)),
                ('ville', models.CharField(blank=True, help_text='Ex: Goma, Bukavu, Bujumbura, Kigali', max_length=100, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('noms_jumeaux_lies', models.TextField(blank=True, help_text='Noms des jumeaux/triplés (séparés par des virgules)', null=True)),
                ('nom_papa', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_maman', models.CharField(blank=True, max_length=100, null=True)),
                ('etat_civil', models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20, null=True)),
                ('statut_pro', models.CharField(blank=True, choices=[('etudiant', 'Étudiant'), ('salarie', 'Salarié'), ('independant', 'Indépendant'), ('sans_emploi', 'Sans emploi'), ('autre', 'Autre')], max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('type_roles', models.CharField(blank=True, default='', help_text='parent,jumeau ou parent ou jumeau', max_length=50)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_cotisation', models.CharField(choices=[('mensuelle', 'Cotisation mensuelle'), ('speciale', 'Cotisation spéciale (activité)')], default='mensuelle', max_length=20)),
                ('mois', models.DateField(blank=True, help_text='Premier jour du mois (ex: 2026-05-01)', null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (€)')),
                ('periode', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('annuelle', 'Annuelle')], default='mensuelle', max_length=20, verbose_name='Périodicité')),
                ('methode_paiement', models.CharField(blank=True, max_length=50, null=True, verbose_name='Méthode de paiement')),
                ('justificatif', models.ImageField(blank=True, null=True, upload_to='justificatifs/', verbose_name='Capture écran paiement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaire_rejet', models.TextField(blank=True, null=True, verbose_name='Motif du rejet')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('date_paiement', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('notification_envoyee', models.BooleanField(default=False, verbose_name='Notification envoyée')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Membre')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.evenement', verbose_name='Événement lié')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL personnalisée')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('extrait', models.TextField(blank=True, max_length=300, null=True, verbose_name='Extrait (résumé)')),
                ('categorie', models.CharField(choices=[('annonce', 'Annonce officielle'), ('evenement', 'Retour sur événement'), ('temoignage', 'Témoignage'), ('partenariat', 'Partenariat'), ('appel', 'Appel à participation'), ('autre', 'Autre')], default='annonce', max_length=50, verbose_name='Catégorie')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='actualites/', verbose_name='Image principale')),
                ('est_publie', models.BooleanField(default=True, verbose_name='Publié ?')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('evenement_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.evenement', verbose_name='Événement lié')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
    ]
