# Generated by Django 6.0.4 on 2026-04-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('noms_jumeaux_lies', models.TextField(blank=True, help_text='Noms des jumeaux/triplés (séparés par des virgules)', null=True)),
                ('nom_papa', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_maman', models.CharField(blank=True, max_length=100, null=True)),
                ('etat_civil', models.CharField(blank=True, choices=[('celibataire', 'Célibataire'), ('marie', 'Marié(e)'), ('divorce', 'Divorcé(e)'), ('veuf', 'Veuf/Veuve')], max_length=20, null=True)),
                ('statut_pro', models.CharField(blank=True, choices=[('etudiant', 'Étudiant'), ('salarie', 'Salarié'), ('independant', 'Indépendant'), ('sans_emploi', 'Sans emploi'), ('autre', 'Autre')], max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('type_roles', models.CharField(help_text='parent,jumeau ou parent ou jumeau', max_length=50)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
