# Generated by Django 6.0.4 on 2026-05-09 14:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cellule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom de la cellule')),
                ('quartier', models.CharField(max_length=100, verbose_name='Quartier')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(max_length=50, verbose_name='Pays')),
                ('responsable', models.CharField(max_length=100, verbose_name='Nom du responsable')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone du responsable')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('est_active', models.BooleanField(default=True, verbose_name='Cellule active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Cellule',
                'verbose_name_plural': 'Cellules',
                'ordering': ['pays', 'ville', 'quartier'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_debut', models.DateTimeField(db_index=True, verbose_name='Date de début')),
                ('date_fin', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('lieu', models.CharField(max_length=200, verbose_name='Lieu')),
                ('statut', models.CharField(choices=[('a_venir', 'À venir'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('annule', 'Annulé')], db_index=True, default='a_venir', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='evenements/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom du partenaire')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('pays', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pays')),
                ('site_web', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('ordre_affichage', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('nom_complet', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Photo de profil')),
                ('pays', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pays')),
                ('ville', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse complète')),
                ('type_roles', models.CharField(blank=True, default='', max_length=50, verbose_name='Rôles')),
                ('nom_jumeau_lie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de mon jumeau/ma jumelle')),
                ('noms_enfants_jumeaux', models.TextField(blank=True, null=True, verbose_name='Noms de mes enfants jumeaux')),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True, verbose_name='Genre')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
            },
        ),
        migrations.CreateModel(
            name='Cotisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre de la cotisation')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('mensuelle', 'Mensuelle'), ('speciale', 'Spéciale')], max_length=20, verbose_name='Type')),
                ('obligatoire', models.BooleanField(default=False, verbose_name='Cotisation obligatoire')),
                ('numero_paiement', models.CharField(db_index=True, max_length=100, verbose_name='Numéro de compte / RIB')),
                ('nom_beneficiaire', models.CharField(blank=True, max_length=200, null=True, verbose_name='Intitulé du compte / Nom du bénéficiaire')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validée')], db_index=True, default='brouillon', max_length=20, verbose_name='Statut')),
                ('date_debut', models.DateField(db_index=True, verbose_name='Date de début')),
                ('date_fin', models.DateField(db_index=True, verbose_name='Date de fin')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations_creees', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations', to='core.evenement', verbose_name='Événement lié (optionnel)')),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'permissions': [('can_validate_cotisation', 'Peut valider une cotisation')],
            },
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL personnalisée')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('extrait', models.TextField(blank=True, max_length=300, null=True, verbose_name='Extrait (résumé)')),
                ('categorie', models.CharField(choices=[('annonce', 'Annonce officielle'), ('evenement', 'Retour sur événement'), ('temoignage', 'Témoignage'), ('partenariat', 'Partenariat'), ('appel', 'Appel à participation'), ('autre', 'Autre')], default='annonce', max_length=50, verbose_name='Catégorie')),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='actualites/', verbose_name='Image principale')),
                ('est_publie', models.BooleanField(default=True, verbose_name='Publié ?')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('evenement_lie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.evenement', verbose_name='Événement lié')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant payé (€)')),
                ('preuve_paiement', models.ImageField(upload_to='preuves/', verbose_name='Preuve de paiement')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validée'), ('rejetee', 'Rejetée')], db_index=True, default='en_attente', max_length=20, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, null=True, verbose_name='Commentaire (rejet, etc.)')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='Membre')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.cotisation', verbose_name='Cotisation concernée')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'permissions': [('can_validate_contribution', 'Peut valider une contribution')],
                'indexes': [models.Index(fields=['statut'], name='core_contri_statut_a3b59c_idx'), models.Index(fields=['cotisation', 'statut'], name='core_contri_cotisat_7a6561_idx')],
                'unique_together': {('membre', 'cotisation')},
            },
        ),
        migrations.AddIndex(
            model_name='cotisation',
            index=models.Index(fields=['statut', 'date_debut'], name='core_cotisa_statut_f8da51_idx'),
        ),
    ]
