# Generated by Django 6.0.4 on 2026-04-29 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pays',
            field=models.CharField(choices=[('RDC', 'République Démocratique du Congo'), ('Rwanda', 'Rwanda'), ('Burundi', 'Burundi')], default='RDC', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='ville',
            field=models.CharField(blank=True, help_text='Ex: Goma, Bukavu, Bujumbura, Kigali', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='adresse',
            field=models.TextField(help_text='Commune, Quartier, Avenue'),
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('nom_complet', 'email')},
        ),
    ]
