# Generated by Django 6.0.4 on 2026-05-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, null=True, verbose_name='Genre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='noms_enfants_jumeaux',
            field=models.TextField(blank=True, null=True, verbose_name='Noms de mes enfants jumeaux'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_roles',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Rôles'),
        ),
    ]
