# Generated by Django 6.0.4 on 2026-05-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_date_naissance_user_genre_and_more'),
    ]

    operations = [
    ]
