# Generated by Django 6.0.4 on 2026-04-29 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_pays_user_ville_alter_user_adresse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('est_membre', models.BooleanField(default=False, verbose_name="Est membre de l'association ?")),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant (€)')),
                ('methode_paiement', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('especes', 'Espèces'), ('virement', 'Virement bancaire'), ('autre', 'Autre')], max_length=50, verbose_name='Méthode de paiement')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message (optionnel)')),
                ('date_don', models.DateTimeField(auto_now_add=True, verbose_name='Date du don')),
                ('lien_membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user', verbose_name='Membre (si déjà inscrit)')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-date_don'],
            },
        ),
    ]
