"""
Django settings for ajgl_project project.
Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path
import os
import dj_database_url
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==========================================
# SECURITY WARNING: keep the secret key used in production secret!
# ==========================================
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-218u3ppvzbvz1jmec@p+8%ep*f&e%qdsb5k*ui)ss*47&osokg')

# ==========================================
# SECURITY WARNING: don't run with debug turned on in production!
# ==========================================
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ==========================================
# ALLOWED HOSTS
# ==========================================
ALLOWED_HOSTS = ['*', '.onrender.com', 'localhost', '127.0.0.1']

# ==========================================
# CSRF Trusted Origins (important pour Render)
# ==========================================
CSRF_TRUSTED_ORIGINS = [
    'https://*.onrender.com',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# ==========================================
# Application definition
# ==========================================
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third party apps
    'django_extensions',
    'cloudinary_storage',
    'cloudinary',
    'crispy_forms',
    'crispy_tailwind',
    # Local apps
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ajgl_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ajgl_project.wsgi.application'

# ==========================================
# Database Configuration - PostgreSQL (Render) ou SQLite (local)
# ==========================================
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # Production: PostgreSQL sur Render
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,  # Vérifie la santé de la connexion
            ssl_require=True  # Render nécessite SSL pour PostgreSQL
        )
    }
else:
    # Développement local: SQLite (optionnel)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# ==========================================
# Password validation
# ==========================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ==========================================
# Internationalization
# ==========================================
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Africa/Lubumbashi'
USE_I18N = True
USE_TZ = True

# ==========================================
# Static files (CSS, JavaScript, Images)
# ==========================================
STATIC_URL = '/static/'

if DEBUG:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, 'core/static')]
else:
    STATICFILES_DIRS = []

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_USE_FINDERS = True
WHITENOISE_MANIFEST_STRICT = False

# ==========================================
# Media files (uploads)
# ==========================================
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==========================================
# Cloudinary Configuration
# ==========================================
if not DEBUG and os.environ.get('CLOUDINARY_URL'):
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# ==========================================
# Crispy forms configuration
# ==========================================
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

# ==========================================
# Custom User Model
# ==========================================
AUTH_USER_MODEL = 'core.User'

# ==========================================
# Authentication URLs
# ==========================================
LOGIN_URL = 'connexion'
LOGIN_REDIRECT_URL = 'tableau-bord'
LOGOUT_REDIRECT_URL = 'accueil'
SESSION_COOKIE_AGE = 1800 
SESSION_SAVE_EVERY_REQUEST = True

# ==========================================
# Security settings for production
# ==========================================
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_HSTS_SECONDS = 31536000 
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True